postgres:
  host: localhost
  user: postgres
  password: postgres
  name: engine
  port: 5445
  ssl_mode: disable
  max_open_connections: 20
  max_idle_connections: 20
  auto_migrate: true

kafka:
  brokers:
    - localhost:9092
  group_id: sagaflow-orchestrator
  client_id: sagaflow-orchestrator-1
  step_result_topic: saga.step.result
  dial_timeout: 5s
  read_timeout: 5s
  commit_interval: 0
  start_offset: 0

runner:
  sagas_dir_path: ./sagas
  hostname: instance1
  workers_num: 3
  batch_size: 4
  empty_batch_delay: 1s
  lock_timeout: 10s

backoffice:
  port: 8080