// Package backoffice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package backoffice

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SagaStatus.
const (
	COMPENSATED  SagaStatus = "COMPENSATED"
	COMPENSATING SagaStatus = "COMPENSATING"
	COMPLETED    SagaStatus = "COMPLETED"
	FAILED       SagaStatus = "FAILED"
	INCONSISTENT SagaStatus = "INCONSISTENT"
	PENDING      SagaStatus = "PENDING"
	RUNNING      SagaStatus = "RUNNING"
)

// Valid indicates whether the value is a known member of the SagaStatus enum.
func (e SagaStatus) Valid() bool {
	switch e {
	case COMPENSATED:
		return true
	case COMPENSATING:
		return true
	case COMPLETED:
		return true
	case FAILED:
		return true
	case INCONSISTENT:
		return true
	case PENDING:
		return true
	case RUNNING:
		return true
	default:
		return false
	}
}

// Feed defines model for Feed.
type Feed struct {
	Items []SagaInfo `json:"items"`

	// PaginationToken Токен для запроса следующей страницы
	PaginationToken string `json:"paginationToken"`
}

// FeedCount defines model for FeedCount.
type FeedCount struct {
	// Count Общее число записей в выборке
	Count int64 `json:"count"`
}

// SagaInfo defines model for SagaInfo.
type SagaInfo struct {
	SagaId   openapi_types.UUID `json:"sagaId"`
	SagaName string             `json:"sagaName"`
	Status   SagaStatus         `json:"status"`
}

// SagaStartRequest defines model for SagaStartRequest.
type SagaStartRequest struct {
	InitialContext map[string]interface{} `json:"initialContext"`
	SagaName       string                 `json:"sagaName"`
	SagaVersion    string                 `json:"sagaVersion"`
}

// SagaStartResponse defines model for SagaStartResponse.
type SagaStartResponse struct {
	SagaId openapi_types.UUID `json:"sagaId"`
}

// SagaStatus defines model for SagaStatus.
type SagaStatus string

// Count Размер страницы
type Count = int

// PaginationToken Токен пагинации
type PaginationToken = string

// Statuses defines model for statuses.
type Statuses = []SagaStatus

// GetFeedParams defines parameters for GetFeed.
type GetFeedParams struct {
	Count Count `form:"count" json:"count"`

	// Statuses Список статусов для фильтрации
	Statuses *Statuses `form:"statuses,omitempty" json:"statuses,omitempty"`
}

// GetFeedPagingParams defines parameters for GetFeedPaging.
type GetFeedPagingParams struct {
	PaginationToken PaginationToken `form:"paginationToken" json:"paginationToken"`
}

// StartSagaJSONRequestBody defines body for StartSaga for application/json ContentType.
type StartSagaJSONRequestBody = SagaStartRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /feed)
	GetFeed(c *gin.Context, params GetFeedParams)

	// (GET /feed/count)
	GedFeedCount(c *gin.Context)

	// (GET /feed/p)
	GetFeedPaging(c *gin.Context, params GetFeedPagingParams)

	// (POST /start)
	StartSaga(c *gin.Context)

	// (GET /status/{sagaId})
	GetSagaStatus(c *gin.Context, sagaId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetFeed operation middleware
func (siw *ServerInterfaceWrapper) GetFeed(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFeedParams

	// ------------- Required query parameter "count" -------------

	if paramValue := c.Query("count"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument count is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "count", c.Request.URL.Query(), &params.Count, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter count: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "statuses" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "statuses", c.Request.URL.Query(), &params.Statuses, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter statuses: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFeed(c, params)
}

// GedFeedCount operation middleware
func (siw *ServerInterfaceWrapper) GedFeedCount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GedFeedCount(c)
}

// GetFeedPaging operation middleware
func (siw *ServerInterfaceWrapper) GetFeedPaging(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFeedPagingParams

	// ------------- Required query parameter "paginationToken" -------------

	if paramValue := c.Query("paginationToken"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument paginationToken is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "paginationToken", c.Request.URL.Query(), &params.PaginationToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter paginationToken: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFeedPaging(c, params)
}

// StartSaga operation middleware
func (siw *ServerInterfaceWrapper) StartSaga(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartSaga(c)
}

// GetSagaStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSagaStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "sagaId" -------------
	var sagaId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sagaId", c.Param("sagaId"), &sagaId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sagaId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSagaStatus(c, sagaId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/feed", wrapper.GetFeed)
	router.GET(options.BaseURL+"/feed/count", wrapper.GedFeedCount)
	router.GET(options.BaseURL+"/feed/p", wrapper.GetFeedPaging)
	router.POST(options.BaseURL+"/start", wrapper.StartSaga)
	router.GET(options.BaseURL+"/status/:sagaId", wrapper.GetSagaStatus)
}

type GetFeedRequestObject struct {
	Params GetFeedParams
}

type GetFeedResponseObject interface {
	VisitGetFeedResponse(w http.ResponseWriter) error
}

type GetFeed200JSONResponse Feed

func (response GetFeed200JSONResponse) VisitGetFeedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GedFeedCountRequestObject struct {
}

type GedFeedCountResponseObject interface {
	VisitGedFeedCountResponse(w http.ResponseWriter) error
}

type GedFeedCount200JSONResponse FeedCount

func (response GedFeedCount200JSONResponse) VisitGedFeedCountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFeedPagingRequestObject struct {
	Params GetFeedPagingParams
}

type GetFeedPagingResponseObject interface {
	VisitGetFeedPagingResponse(w http.ResponseWriter) error
}

type GetFeedPaging200JSONResponse Feed

func (response GetFeedPaging200JSONResponse) VisitGetFeedPagingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StartSagaRequestObject struct {
	Body *StartSagaJSONRequestBody
}

type StartSagaResponseObject interface {
	VisitStartSagaResponse(w http.ResponseWriter) error
}

type StartSaga202JSONResponse SagaStartResponse

func (response StartSaga202JSONResponse) VisitStartSagaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type GetSagaStatusRequestObject struct {
	SagaId openapi_types.UUID `json:"sagaId"`
}

type GetSagaStatusResponseObject interface {
	VisitGetSagaStatusResponse(w http.ResponseWriter) error
}

type GetSagaStatus200JSONResponse SagaInfo

func (response GetSagaStatus200JSONResponse) VisitGetSagaStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /feed)
	GetFeed(ctx context.Context, request GetFeedRequestObject) (GetFeedResponseObject, error)

	// (GET /feed/count)
	GedFeedCount(ctx context.Context, request GedFeedCountRequestObject) (GedFeedCountResponseObject, error)

	// (GET /feed/p)
	GetFeedPaging(ctx context.Context, request GetFeedPagingRequestObject) (GetFeedPagingResponseObject, error)

	// (POST /start)
	StartSaga(ctx context.Context, request StartSagaRequestObject) (StartSagaResponseObject, error)

	// (GET /status/{sagaId})
	GetSagaStatus(ctx context.Context, request GetSagaStatusRequestObject) (GetSagaStatusResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetFeed operation middleware
func (sh *strictHandler) GetFeed(ctx *gin.Context, params GetFeedParams) {
	var request GetFeedRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetFeed(ctx, request.(GetFeedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFeed")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetFeedResponseObject); ok {
		if err := validResponse.VisitGetFeedResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GedFeedCount operation middleware
func (sh *strictHandler) GedFeedCount(ctx *gin.Context) {
	var request GedFeedCountRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GedFeedCount(ctx, request.(GedFeedCountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GedFeedCount")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GedFeedCountResponseObject); ok {
		if err := validResponse.VisitGedFeedCountResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFeedPaging operation middleware
func (sh *strictHandler) GetFeedPaging(ctx *gin.Context, params GetFeedPagingParams) {
	var request GetFeedPagingRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetFeedPaging(ctx, request.(GetFeedPagingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFeedPaging")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetFeedPagingResponseObject); ok {
		if err := validResponse.VisitGetFeedPagingResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartSaga operation middleware
func (sh *strictHandler) StartSaga(ctx *gin.Context) {
	var request StartSagaRequestObject

	var body StartSagaJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			ctx.Status(http.StatusBadRequest)
			ctx.Error(err)
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StartSaga(ctx, request.(StartSagaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartSaga")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StartSagaResponseObject); ok {
		if err := validResponse.VisitStartSagaResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSagaStatus operation middleware
func (sh *strictHandler) GetSagaStatus(ctx *gin.Context, sagaId openapi_types.UUID) {
	var request GetSagaStatusRequestObject

	request.SagaId = sagaId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSagaStatus(ctx, request.(GetSagaStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSagaStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetSagaStatusResponseObject); ok {
		if err := validResponse.VisitGetSagaStatusResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
